export const DATA = [
    {
        id: 1,
        title: 'Площадь квадрата',
        img: require('../assets/fig1.png'),
        formulaTitle: 'S=a^2',
        params: ['a'],
        formula: (param1, param2, param3) => (param1 * param1),
    },
    {
        id: 2,
        title: 'Площадь прямоугольника',
        img: require('../assets/fig2.png'),
        formulaTitle: 'S=a * b',
        params: ['a','b'],
        formula: (param1, param2, param3) => (param1 * param2),
    },
    {
        id: 3,
        title: 'Площадь круга',
        img: require('../assets/fig3.png'),
        formulaTitle: 'S=\\pi * R^2',
        params: ['R'],
        formula: (param1, param2, param3) => (3.14 * param1 * param1),
    },
    {
        id: 4,
        title: 'Площадь круга',
        img: require('../assets/fig4.png'),
        formulaTitle: 'S=\\pi * \\frac{D^2}{4}',
        params: ['D'],
        formula: (param1, param2, param3) => (3.14 * param1 * param1 / 4),
    },
    {
        id: 5,
        title: 'Площадь треугольника',
        img: require('../assets/fig5.png'),
        formulaTitle: 'S=\\frac{a * h}{2}',
        params: ['a', 'h'],
        formula: (param1, param2, param3) => (param1 * param2 / 2),
    },
    {
        id: 6,
        title: 'Площадь треугольника',
        img: require('../assets/fig6.png'),
        formulaTitle: 'S=\\sqrt{p(p-a)(p-b)(p-c)}',
        formulaSubTitle: 'p= (a + b + c) / 2',
        params: ['a', 'b', 'c'],
        formula: (param1, param2, param3) => (Math.sqrt(((param1+param2+param3)/2)*(((param1+param2+param3)/2)-param1)*(((param1+param2+param3)/2)-param2)*(((param1+param2+param3)/2)-param3))),
    },
    {
        id: 7,
        title: 'Площадь треугольника',
        img: require('../assets/fig7.png'),
        formulaTitle: 'S= (a * b) / 2',
        params: ['a', 'b'],
        formula: (param1, param2, param3) => (param1 * param2 / 2),
    },
    {
        id: 8,
        title: 'Площадь треугольника',
        img: require('../assets/fig8.png'),
        formulaTitle: 'S= (a*b / 2) * sin(c)',
        params: ['a', 'b', 'c'],
        formula: (param1, param2, param3) => ((param1 * param2 / 2)*Math.sin(param3*3.14/180)),
    },
    {
        id: 9,
        title: 'Площадь трапеции',
        img: require('../assets/fig9.png'),
        formulaTitle: 'S= \\frac{a+b}{2}*\\sqrt{c^2-\\frac{(a-b)^2}{4}}',
        params: ['a', 'b', 'c'],
        formula: (param1, param2, param3) => (((param1 + param2)/2)*(Math.sqrt((param3 * param3)-((param1-param2)*(param1-param2)/4)))),
    },
    {
        id: 10,
        title: 'Площадь бублика',
        img: require('../assets/fig10.png'),
        formulaTitle: 'S= \\pi * ( R^2 - r^2)',
        params: ['R', 'r'],
        formula: (param1, param2, param3) => (3.14*((param1*param1)-(param2*param2))),
    },
];